name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    uses: Platform-System/Platform.CI-CD/.github/workflows/dotnet-build-template.yml@main
    with:
      project_path: 'Platform.ProductCoverUpload.Function.csproj'

  deploy:
    uses: Platform-System/Platform.CI-CD/.github/workflows/azure-function-flex-deploy-template.yml@main
    needs: build
    secrets:
      publish_profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
    with:
      project_path: 'Platform.ProductCoverUpload.Function.csproj'
      function_app_name: 'fa-product-cover-upload'

